# 📆 2024-10-29


# 🔔 스크럼

- 학습 목표 1 : Promise

<br/>

# 🚀 Today I Learned

## Promise

Fetch API에 대해 알아보던 중, fetch()의 반환 값으로 Promise 객체를 반환한다는 사실을 알게 되었다. 

Promise는 ES6에서 등장한 비동기 처리 패턴으로 기존 콜백 함수 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다고 한다.

## 등장 배경: 콜백 함수의 단점 

### 콜백 헬(Callback Hell)

JS에서 DOM 이벤트, Timer 함수, Ajax 요청과 같은 비동기 처리 모델은 빈번하게 사용된다.

비동기 처리 모델은 실행 완료를 기다리지 않고 다음 태스크를 실행 하는데, 이로 인해 비동기 함수 내에서 처리 결과를 반환하면 기대한 대로 동작하지 않는다.

```javascript
// 비동기 함수 (setTimeout을 사용해 비동기 작업을 시뮬레이션)
function fetchData() {
    setTimeout(() => {
        return "Data fetched"; // 결과를 반환
    }, 1000);
}

// 비동기 함수 호출
const result = fetchData();
console.log(result); // 기대한 결과가 아닌 undefined가 출력됨
```

fetchData가 반환하는 "Data fetched"는 setTimeout의 콜백 함수가 반환한다. 

그러나, setTimeout의 콜백 함수는 설정된 1초가 지났다고 해서 곧바로 실행되는 것이 아니라 일단 태스크 큐에 들어가고 이벤트 루프에 의해 콜 스택이 비었을 때 실행된다.

이러한 이유로 setTimeout의 시간을 매우 짧게 설정해 console.log 호출 시점 이전에 setTimeout 타이머가 만료되었다고 해도 fetchData 함수가 종료하면 곧바로 console.log가 실행되기 때문에 콜백 함수는 console.log가 종료된 이후에 실행된다.

즉, 비동기 함수가 처리 결과를 반환하는 경우 실행 순서가 보장되지 않기 때문에 반환 결과로 후속 처리를 할 수 없다.

따라서, 비동기 함수의 처리 결과에 대한 처리는 비동기 함수의 콜백 함수 내에서 처리해야 하고 이로 인해 콜백 헬(Callback Hell)이 발생한다. 

콜백 헬은 코드의 가독성을 나쁘게 하고 복잡도를 증가시켜 실수를 유발하는 원인이 되며 에러 처리가 곤란해진다.

### 에러 처리의 한계

```javascript
try {
	setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
	console.log('에러 캐치 불가');
}
```
콜백 방식의 비동기 처리가 갖는 문제점 중 하나는 에러 처리가 곤란한 것이라고 한다.

try 블록 내에서 setTimeout 함수가 실행되면 1초 후에 콜백 함수가 실행되고 이 콜백 함수는 예외를 발생시킨다. 하지만, 발생된 예외는 catch 블록에서 캐치되지 않는다.

setTimeout 함수는 비동기 함수이므로 콜백 함수가 실행될 때까지 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다. 

이후 setTimeout의 콜백 함수는 이벤트 루프에 의해 태스크 큐에서 콜 스택으로 이동되어 실행된다.

이는 setTimeout의 콜백 함수의 호출자가 setTimeout이 아니라는 것을 의미하는데, setTimeout의 콜백 함수의 호출자가 setTimeout이라면 콜 스택에 setTimeout이 존재해야 하기 때문이다.

예외는 호출자 방향으로 전파된다. setTimeout의 콜백 함수의 호출자는 setTimeout이 아니기 때문에 catch 블록에서 예외는 캐치되지 않고 종료된다.

이러한 문제를 극복하기 위해 ES6에서 Promise가 채택되었고 IE를 제외한 대부분의 브라우저가 지원하고 있다.

## Promise

Promise는 new Promise()로 생성할 수 있으며, 비동기 작업을 수행하는 콜백 함수를 인자로 전달해야 한다. 

이 콜백 함수는 두 개의 인자를 받는데, 하나는 resolve(성공 시 호출)이고 다른 하나는 reject(실패 시 호출)이다.

```javascript
const promise = new Promise((resolve, reject) => {
		// 비동기 작업 수행
		const success = true;
		
		if (success) {
				resolve("작업 성공!");
		} else {
				reject("작업 실패ㅜ");
		}
});
```

Promise는 비동기 작업 처리가 성공했는지 또는 실패했는지 등의 대한 상태 정보를 갖는다. 

Promise의 상태 정보는 아래의 표에 정리해두었다.

| 상태 | 의미 | 구현 |
| --- | --- | --- |
| pending | 비동기 처리가 아직 완료되지 않은 상태 | resolve 또는 reject 함수가 아직 호출되지 않은 상태 |
| fulfilled | 비동기 처리가 성공한 상태 | resolve 함수가 호출된 상태 |
| rejected | 비동기 처리가 실패한 상태 | reject 함수가 호출된 상태 |

### Promise의 후속 처리 메서드

Promise 객체를 반환하는 함수를 호출하는 측에서는 Promise의 후속 처리 메서드를 통해 비동기 처리 결과 또는 에러 메시지를 전달받아 처리한다.

Promise 객체는 상태 정보에 따라 후속 처리 메서드를 체이닝 방식으로 호출한다.

[then]
then 메서드는 두 개의 콜백 함수를 인자로 전달 받는다. 한 개의 인자를 전달 받는 경우는 fulfilled 상태에서 호출될 것으로 간주한다.

첫 번째 콜백 함수는 fulfilled 상태일 때 호출되고 두 번째 콜백 함수는 rejected 상태일 때 호출된다.

그리고 then 메서드는 항상 새로운 Promise 객체를 반환한다. 이 Promise는 다음 then 메서드나 catch 메서드에서 사용할 수 있는 체이닝 용도의 Promise이다.

[catch]
catch 메서드 내부적으로 then(undefined, onRejected)을 호출한다. 따라서, 새로운 Promise 객체를 반환한다.

모든 then 메서드를 호출한 이후 catch 메서드를 호출하면 비동기 처리에서 발생한 에러뿐 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.

따라서, 에러 처리는 catch 메서드를 사용하는 것이 권장된다.

[finally]
finally 메서드는 성공 여부와 관계없이 항상 마지막에 실행된다. 리소스 해제 등 후처리에 사용할 수 있다.

## 결론

![https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/promises.png](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/promises.png)

- Promise는 ES6에서 도입된 비동기 처리 패턴으로, 콜백 함수의 단점인 콜백 헬과 에러 처리의 한계를 해결하기 위해 등장했다.

- Promise 객체는 pending, fulfilled, rejected 세 가지 상태를 가진다.

- then, catch, finally 메서드를 통해 비동기 처리 결과를 효과적으로 다룰 수 있다.

- 체이닝을 통해 비동기 작업을 순차적으로 처리할 수 있어 코드의 가독성과 유지보수성이 향상된다.

- 에러 처리는 catch 메서드를 사용하는 것이 권장된다.

# 🔥 오늘의 도전 과제와 해결 방법

- Promise에 대해 학습 !

# 🗨️ 오늘의 회고

- 조금씩 공부하는 시간이 늘어나는 것 같아서 뿌듯하다.
- 시간 배분을 잘해야겠다.


<!--
- 오늘의 학습 경험에 대한 자유로운 생각이나 느낀 점을 기록합니다.
- 성공적인 점, 개선해야 할 점, 새롭게 시도하고 싶은 방법 등을 포함할 수 있습니다.-->

